# Generated by Django 2.2.28 on 2024-03-11 16:02

from django.db import migrations, models
import symphonet1.models


class Migration(migrations.Migration):

    dependencies = [
        ('symphonet1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='song',
            field=models.CharField(default=' ', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0, validators=[symphonet1.models.limit]),
        ),
    ]
